version: "3"
services:
  spring:
    container_name: qapp_spring
    image: jhignas/qapp_spring:toDocker
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    container_name: qapp_postgres
    image: jhignas/qapp_postgres
    ports:
      - "6000:5432"