CREATE SEQUENCE IF NOT EXISTS question_sequence MINVALUE 1000;

CREATE TABLE IF NOT EXISTS  QUESTIONS (
	Q_ID 	INT 	PRIMARY KEY DEFAULT nextval('question_sequence') ,
	Q_TEXT 	VARCHAR(100) 	NOT NULL,
	Q_TAGS 	VARCHAR(100) 	NOT NULL
);