SQL FILE

	DROP USER IF EXISTS qapp;

	CREATE USER qapp WITH PASSWORD 'qapp' CREATEDB;

	DROP DATABASE IF EXISTS QAPP_DB;

	CREATE DATABASE QAPP_DB OWNER QAPP;
	
	\c qapp_db qapp;

	DROP SEQUENCE IF EXISTS question_sequence;

	CREATE SEQUENCE question_sequence;

	DROP TABLE IF EXISTS QUESTIONS;

	CREATE TABLE IF NOT EXISTS  QUESTIONS (
		Q_ID 	INT 	PRIMARY KEY DEFAULT nextval('question_sequence'),
		Q_TEXT 	VARCHAR(100) 	NOT NULL,
		Q_TAGS 	VARCHAR(100) 	NOT NULL
	);